<template>
  <div>
    <span>scroll behavior</span>
    <ul>
      <li>占位列表1</li>
      <li>占位列表2</li>
      <li>占位列表3</li>
      <li>占位列表4</li>
      <li>占位列表5</li>
      <li>占位列表6</li>
      <li>占位列表7</li>
      <li>占位列表8</li>
      <li>占位列表9</li>
      <li>占位列表10</li>
      <li>占位列表11</li>
      <li>占位列表12</li>
      <li>占位列表13</li>
      <li>占位列表14</li>
      <li>占位列表15</li>
      <li>占位列表16</li>
      <li>占位列表17</li>
      <li>占位列表18</li>
      <li>占位列表19</li>
      <li>占位列表20</li>
      <li>占位列表21</li>
      <li>占位列表22</li>
      <li>占位列表23</li>
      <li>占位列表24</li>
      <li>占位列表25</li>
      <li>占位列表26</li>
      <li>占位列表27</li>
      <li>占位列表28</li>
      <li>占位列表29</li>
      <li>占位列表30</li>
      <li>占位列表31</li>
      <li>占位列表32</li>
      <li>占位列表33</li>
      <li>占位列表34</li>
      <li>占位列表35</li>
      <li>占位列表36</li>
      <li>占位列表37</li>
      <li>占位列表38</li>
      <li>占位列表39</li>
      <li>占位列表40</li>
      <li>占位列表41</li>
      <li>占位列表42</li>
      <li>占位列表43</li>
      <li>占位列表44</li>
      <li>占位列表45</li>
      <li>占位列表46</li>
      <li>占位列表47</li>
      <li>占位列表48</li>
      <li>占位列表49</li>
      <li>占位列表50</li>
      <li>占位列表51</li>
      <li>占位列表52</li>
      <li>占位列表53</li>
      <li>占位列表54</li>
      <li>占位列表55</li>
      <li>占位列表56</li>
      <li>占位列表57</li>
      <li>占位列表58</li>
      <li>占位列表59</li>
      <li>占位列表60</li>
      <li>占位列表61</li>
      <li>占位列表62</li>
      <li>占位列表63</li>
      <li>占位列表64</li>
      <li>占位列表65</li>
      <li>占位列表66</li>
      <li>占位列表67</li>
      <li>占位列表68</li>
      <li>占位列表69</li>
      <li>占位列表70</li>
      <li>占位列表71</li>
      <li>占位列表72</li>
      <li>占位列表73</li>
      <li>占位列表74</li>
      <li>占位列表75</li>
      <li>占位列表76</li>
      <li>占位列表77</li>
      <li>占位列表78</li>
      <li>占位列表79</li>
      <li>占位列表80</li>
      <li>占位列表81</li>
      <li>占位列表82</li>
      <li>占位列表83</li>
      <li>占位列表84</li>
      <li>占位列表85</li>
      <li>占位列表86</li>
      <li>占位列表87</li>
      <li>占位列表88</li>
      <li>占位列表89</li>
      <li>占位列表90</li>
      <li>占位列表91</li>
      <li>占位列表92</li>
      <li>占位列表93</li>
      <li>占位列表94</li>
      <li>占位列表95</li>
      <li>占位列表96</li>
      <li>占位列表97</li>
      <li>占位列表98</li>
      <li>占位列表99</li>
      <li>占位列表100</li>
    </ul>
  </div>
</template>

<script>
export default {};
</script>

<style>
</style>
